import json
from pathlib import Path
from typing import Dict, Optional, Any
import logging

logger = logging.getLogger(__name__)


class MetadataManager:
    """Manages metadata for header-based error information extraction."""
    
    def __init__(self, metadata_file_path: Optional[str] = None):
        self.metadata = {}
        self.transaction_map = {}
        if metadata_file_path:
            self.load_metadata(metadata_file_path)
    
    def load_metadata(self, file_path: str):
        """Load metadata from JSON file generated by payload creation."""
        try:
            with open(file_path, 'r') as f:
                self.metadata = json.load(f)
            
            if 'metadata' in self.metadata and 'transactions' in self.metadata['metadata']:
                for transaction in self.metadata['metadata']['transactions']:
                    st_control = transaction.get('st_control_number')
                    if st_control:
                        self.transaction_map[st_control] = transaction
                        
            logger.info(f"Loaded metadata for {len(self.transaction_map)} transactions")
            
        except Exception as e:
            logger.error(f"Failed to load metadata from {file_path}: {e}")
            self.metadata = {}
            self.transaction_map = {}
    
    def get_error_info(self, st_control_number: str) -> Dict[str, str]:
        """Extract error information for headers based on ST control number."""
        transaction = self.transaction_map.get(st_control_number)
        if not transaction:
            return {}
        
        headers = {
            "X-Transaction-Number": st_control_number,
            "X-Beneficiary-ID": transaction.get('beneficiary_id', ''),
            "X-Has-Errors": str(transaction.get('error_injected', False)).lower()
        }
        
        if transaction.get('error_injected'):
            error_types = []
            if transaction.get('error_segment'):
                error_types.append(f"segment:{transaction['error_segment']}")
            if transaction.get('error_type'):
                error_types.append(f"type:{transaction['error_type']}")
            
            if error_types:
                headers["X-Error-Types"] = ",".join(error_types)
            
            if transaction.get('line_number_in_file'):
                headers["X-Error-Line"] = str(transaction['line_number_in_file'])
        
        if transaction.get('provider_npi'):
            headers["X-Provider-NPI"] = transaction['provider_npi']
            
        return headers
    
    def get_error_summary(self) -> Dict[str, Any]:
        """Get overall error summary for reporting."""
        if not self.metadata or 'metadata' not in self.metadata:
            return {}
            
        metadata = self.metadata['metadata']
        return {
            "total_transactions": len(self.transaction_map),
            "total_errors": metadata.get('error_summary', {}).get('total_errors', 0),
            "error_rate": metadata.get('error_summary', {}).get('error_rate_actual', 0),
            "error_breakdown": metadata.get('error_breakdown', {}),
            "clean_transactions": len(metadata.get('transactions_by_error_status', {}).get('clean', [])),
            "error_transactions": len(metadata.get('transactions_by_error_status', {}).get('with_errors', []))
        }