sonar.projectKey=datagen
sonar.projectName=DataGen Project
sonar.sources=src
sonar.exclusions=**/__pycache__/**,**/.venv/**,**/samples/**
sonar.sourceEncoding=UTF-8
sonar.python.version=3.12
sonar.host.url=http://localhost:9000
sonar.token=squ_988f08a1cc34e7d095bb6a0f2a89e253031a504c