[seed]
faker_seed = 49245
random_seed = 3

[aws]
upload_to_s3 = false
bucket_name = "edi-file-storage"

[database]
backend = "sqlite"
jsonl_path = "localdb.jsonl"
sqlite_path = "localdb.sqlite"

[paths]
download_directory = "Downloads"
family_database_directory = "Output/Local_DB"
edi270_path = "Output/EDI270_Output"
edi837_path = "Output/EDI837_Output"
edi277ca_path = "Output/EDI277CA_Output"
edi835_path = "Output/EDI835_Output"
edi834_path = "Output/EDI834_Output"
edi999_path = "Output/EDI999_Output"

[filenames]
edi270_file_template = "270.VFMP.{year}.{ymd}.{hm}.{claim_id}.{full_date}1.edi"
edi277ca_file_template = "277CA.VFMP.{year}.{ymd}.{hm}.{full_date}1.edi"
edi837_file_template = "837.VFMP.{year}.{ymd}.{hm}.{full_date}1.edi"
edi835_file_template = "835.VFMP.{year}.{ymd}.{hm}.{full_date}1.edi"
edi834_file_template = "834.VFMP.{year}.{ymd}.{hm}.{full_date}1.edi"
edi999_file_template = "999.VFMP.{year}.{ymd}.{hm}.{full_date}1.edi"
statistics_md = "Statistics_Visualizer.md"

[inputs]
toggle_new_line = true
total_error_rate = 0.005
max_beneficiaries = 4
min_beneficiaries = 1
max_deductibles = 100000.0
min_deductibles = 0.0
max_visits = 15
min_visits = 0
initial_beneficiaries = 100000

[constants]
sender_id = "83-1002022"
receiver_id = "841439824"
sponsor_name = "OCC PAYER EDI"
sponsor_id = "841469824"
payer_name = "CLAIMS XM"
payer_id = "831002042"
date_time_fmt_qualifier = "D8"

[edi270_fields]
gs_functional_identifier_code = "HS"
hierarchical_structure_code = "22"
transaction_set_purpose_code = "13"
payer_entity_identifier_code = "PR"
payer_entity_type_qualifier = "2"
payer_id_code_qualifier = "PI"
provider_entity_identifier_code = "1P"
provider_id_code_qualifier = "XX"
subscriber_entity_identifier_code = "IL"
subscriber_entity_type_qualifier = "1"
subscriber_id_code_qualifier = "MI"
dependent_entity_identifier_code = "03"
dependent_entity_type_qualifier = "1"
dtp_qualifier = "291"
eq_service_type_code = "30"

[edi837_fields]
gs_functional_identifier_code = "HC"
bht_structure_code = "19"
bht_purpose_code = "00"
submitter_entity_identifier_code = "41"
submitter_entity_type_qualifier = "2"
submitter_name = "Submitter Group"
submitter_id_code_qualifier = "46"
submitter_id = "133052274"
per_contact_function_code = "IC"
per_communication_number = "2403018701"
receiver_entity_identifier_code = "40"
receiver_entity_type_qualifier = "2"
receiver_name = "Receiver Group"
receiver_id_code_qualifier = "46"
receiver_id = "84146"
billing_provider_entity_identifier_code = "85"
billing_provider_id_code_qualifier = "XX"
ref_billing_provider_qualifier = "EI"
ref_billing_provider_id = "123456789"
sbr_payer_relationship_code = "18"
sbr_group_id = "123456"
subscriber_entity_identifier_code = "IL"
subscriber_entity_type_qualifier = "1"
subscriber_id_code_qualifier = "MI"
payer_entity_identifier_code = "PR"
payer_entity_type_qualifier = "2"
payer_id_code_qualifier = "PI"
payer_address_1 = "123"
payer_address_2 = "Payer Ave"
payer_city = "Payer City"
payer_state = "MD"
payer_zip = "99999"
patient_entity_identifier_code = "QC"
patient_entity_type_qualifier = "1"
clm_charge_amount = "827"
clm_facility_code = "22"
clm_facility_qualifier = "B"
clm_frequency = "1"
ref_claim_qualifier = "D9"
hi_diagnosis_code_qualifier = "BK"
hi_diagnosis_code = "36616"
rendering_provider_entity_identifier_code = "82"
rendering_provider_entity_type_qualifier = "1"
rendering_provider_id_code_qualifier = "XX"
prv_provider_code = "PE"
prv_reference_identification_qualifier = "PXC"
prv_provider_taxonomy_code = "207L00000X"
sv1_procedure_identifier = "HC:00142:QK:QS:P1"
sv1_line_item_charge_amount = "827"
sv1_unit_or_basis_for_measurement_code = "MJ"
sv1_service_unit_count = "1"
dtp_service_date_qualifier = "472"
ref_line_item_qualifier = "6R"

[relationship_map]
Spouse = "01"
Child = "19"
Caregiver = "26"
Ex-Spouse = "25"

[test_size.834]
avg = 10627
std = 13948
min = 1
max = 246778
shape = "NORMAL"

[test_size.270]
avg = 15000
std = 5000
min = 1
max = 75000
shape = "NORMAL"

[logging]
level = "INFO"
directory = "Output/Logs"
filename_template = "TestSuite_{date}.log"