[seed]
faker_seed = 49245
random_seed = 3

[aws]
upload_to_s3 = false
bucket_name = "edi-file-storage"

[database]
backend = "sqlite"
jsonl_path = "localdb.jsonl"
sqlite_path = "localdb.sqlite"

[paths]
download_directory = "Downloads"
family_database_directory = "Output/Local_DB"
edi270_path = "Output/EDI270_Output"
edi837_path = "Output/EDI837_Output"
edi277ca_path = "Output/EDI277CA_Output"
edi835_path = "Output/EDI835_Output"
edi834_path = "Output/EDI834_Output"

[filenames]
edi270_file_template = "270.VFMP.{year}.{ymd}.{hm}.{ssmmm}.{full_date}1.edi"
edi277ca_file_template = "277CA.VFMP.{year}.{ymd}.{hm}.{full_date}1.edi"
edi837_file_template = "837.VFMP.{year}.{ymd}.{hm}.{full_date}1.edi"
edi835_file_template = "835.VFMP.{year}.{ymd}.{hm}.{full_date}1.edi"
edi834_file_template = "834.VFMP.{year}.{ymd}.{hm}.{full_date}1.edi"
statistics_md = "Statistics_Visualizer.md"

[constants]
sender_id = "83-1002022"
receiver_id = "841439824"
sponsor_name = "OCC PAYER EDI"
sponsor_id = "841469824"
payer_name = "CLAIMS XM"
payer_id = "831002042"
date_time_fmt_qualifier = "D8"
toggle_new_line = true
total_error_rate = 0.005
max_beneficiaries = 4
min_beneficiaries = 1
max_deductibles = 100000.0
min_deductibles = 0.0
max_visits = 15
min_visits = 0
initial_beneficiaries = 100000

[relationship_map]
Spouse = "01"
Child = "19"
Caregiver = "26"
Ex-Spouse = "25"

[test_size.834]
avg = 10627
std = 13948
min = 1
max = 246778
shape = "NORMAL"

[test_size.270]
avg = 15000
std = 5000
min = 1
max = 75000
shape = "NORMAL"

[logging]
level = "INFO"
directory = "Output/Logs"
filename_template = "TestSuite_{date}.log"